apiVersion: v1
kind: Service
metadata:
  name: rugpull-detector-service
spec:
  selector:
    app: rugpull-detector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 